import type { LevelDefinition } from './levelTypes';

export const LEVELS: LevelDefinition[] = [
  {
    id: 'basic-betrayal',
    name: 'Basic Betrayal',
    behavior: 'fakeFloorNearDoor',
    spawn: { x: 58, y: 284 },
    platforms: [
      { id: 'floor-left', x: 20, y: 318, w: 482, h: 72 },
      { id: 'bait-tile', x: 500, y: 318, w: 72, h: 72, kind: 'fake' },
      { id: 'door-ledge', x: 570, y: 318, w: 130, h: 72 },
    ],
    spikes: [{ id: 'first-spike', x: 256, y: 286, w: 38, h: 32 }],
    doors: [{ id: 'exit', kind: 'real', x: 642, y: 248, w: 38, h: 70, open: true }],
    signs: [{ id: 'hello', x: 148, y: 246, text: 'Easy first level.' }],
    deathMessages: ['The floor had one job.', 'Welcome to trust issues.'],
  },
  {
    id: 'lying-sign',
    name: 'Lying Sign',
    behavior: 'jumpRevealsSpikes',
    spawn: { x: 58, y: 284 },
    platforms: [{ id: 'floor', x: 20, y: 318, w: 680, h: 72 }],
    spikes: [{ id: 'ceiling-spikes', x: 238, y: 196, w: 154, h: 32, hidden: true, orientation: 'down' }],
    doors: [{ id: 'exit', kind: 'real', x: 642, y: 248, w: 38, h: 70, open: true }],
    signs: [{ id: 'jump-sign', x: 296, y: 248, text: 'Jump!' }],
    jumpTrapZone: { x: 206, y: 235, w: 210, h: 90 },
    deathMessages: ['You obeyed a sign. Rookie move.', 'Reading is dangerous.'],
  },
  {
    id: 'fake-floor',
    name: 'Fake Floor',
    behavior: 'disappearingFloor',
    spawn: { x: 58, y: 284 },
    platforms: [
      { id: 'floor-left', x: 20, y: 318, w: 272, h: 72 },
      { id: 'vanish', x: 290, y: 318, w: 98, h: 72, kind: 'drop' },
      { id: 'floor-right', x: 386, y: 318, w: 314, h: 72 },
    ],
    spikes: [{ id: 'landing-spike', x: 468, y: 286, w: 38, h: 32 }],
    doors: [{ id: 'exit', kind: 'real', x: 642, y: 248, w: 38, h: 70, open: true }],
    signs: [{ id: 'steady', x: 312, y: 250, text: 'Solid.' }],
    deathMessages: ['Solid opinion. Bad floor.', 'That platform left the chat.'],
  },
  {
    id: 'do-not-press',
    name: 'Do Not Press',
    behavior: 'buttonOpensDoor',
    spawn: { x: 58, y: 284 },
    platforms: [{ id: 'floor', x: 20, y: 318, w: 680, h: 72 }],
    spikes: [{ id: 'bait-spike', x: 420, y: 286, w: 38, h: 32 }],
    buttons: [{ id: 'open-button', x: 294, y: 294, w: 66, h: 24, opensDoorId: 'exit' }],
    doors: [{ id: 'exit', kind: 'real', x: 642, y: 248, w: 38, h: 70, open: false }],
    signs: [{ id: 'warning', x: 326, y: 245, text: 'DO NOT PRESS', width: 152 }],
    deathMessages: ['You found a way to lose to a button.', 'The button is innocent. Mostly.'],
  },
  {
    id: 'helpful-button',
    name: 'Helpful Button',
    behavior: 'buttonDropsFloor',
    spawn: { x: 58, y: 284 },
    platforms: [
      { id: 'floor-left', x: 20, y: 318, w: 310, h: 72 },
      { id: 'button-tile', x: 328, y: 318, w: 98, h: 72, kind: 'drop' },
      { id: 'floor-right', x: 424, y: 318, w: 276, h: 72 },
    ],
    spikes: [{ id: 'escape-spike', x: 506, y: 286, w: 38, h: 32 }],
    buttons: [{ id: 'help-button', x: 346, y: 294, w: 66, h: 24, opensDoorId: 'exit', dropsPlatformId: 'button-tile' }],
    doors: [{ id: 'exit', kind: 'real', x: 642, y: 248, w: 38, h: 70, open: false }],
    signs: [{ id: 'help', x: 376, y: 246, text: 'Helpful button' }],
    deathMessages: ['It helped. Technically.', 'Press and leave, not press and nap.'],
  },
  {
    id: 'fake-door',
    name: 'Fake Door',
    behavior: 'fakeDoor',
    spawn: { x: 126, y: 284 },
    platforms: [
      { id: 'floor', x: 20, y: 318, w: 680, h: 72 },
      { id: 'left-fake-wall', x: 20, y: 238, w: 76, h: 80, kind: 'fakeWall' },
    ],
    spikes: [],
    doors: [
      { id: 'real-exit', kind: 'real', x: 38, y: 248, w: 38, h: 70, open: true },
      { id: 'fake-exit', kind: 'fakeDeadly', x: 642, y: 248, w: 38, h: 70, open: true },
    ],
    signs: [{ id: 'nice-door', x: 566, y: 246, text: 'Exit this way' }],
    deathMessages: ['Maybe that wasn\'t the real door.', 'It looked official, though.'],
  },
  {
    id: 'moving-door',
    name: 'Moving Door',
    behavior: 'movingDoor',
    spawn: { x: 58, y: 284 },
    platforms: [
      { id: 'floor', x: 20, y: 318, w: 680, h: 72 },
      { id: 'step-one', x: 220, y: 258, w: 92, h: 22 },
      { id: 'step-two', x: 358, y: 212, w: 104, h: 22 },
      { id: 'right-drop', x: 598, y: 258, w: 102, h: 22 },
    ],
    spikes: [{ id: 'floor-spike', x: 572, y: 286, w: 38, h: 32 }],
    doors: [{ id: 'exit', kind: 'moving', x: 520, y: 248, w: 38, h: 70, open: true }],
    signs: [{ id: 'stand-still', x: 484, y: 246, text: 'Almost done.' }],
    movingDoorStopX: 642,
    deathMessages: ['The door has boundaries.', 'Try meeting it from another angle.'],
  },
  {
    id: 'fake-victory',
    name: 'Fake Victory',
    behavior: 'fakeVictory',
    spawn: { x: 58, y: 284 },
    platforms: [{ id: 'floor', x: 20, y: 318, w: 680, h: 72 }],
    spikes: [{ id: 'final-spike', x: 590, y: 286, w: 38, h: 32, hidden: true }],
    doors: [
      { id: 'fake-win', kind: 'fakeVictory', x: 510, y: 248, w: 38, h: 70, open: true },
      { id: 'real-exit', kind: 'hiddenReal', x: 642, y: 248, w: 38, h: 70, open: false, hidden: true },
    ],
    signs: [{ id: 'final', x: 320, y: 246, text: 'Final door. Promise.', width: 168 }],
    deathMessages: ['The demo almost let you have that.', 'Victory has terms and conditions.'],
  },
];
